/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_HAFenetreReservation (void)
{
  GtkWidget *HAFenetreReservation;
  GtkWidget *HAfixed1;
  GtkWidget *HAentryNom;
  GtkWidget *HAentryPrenom;
  GtkWidget *HAentryCin;
  GtkObject *HAspinbuttonJour_adj;
  GtkWidget *HAspinbuttonJour;
  GtkObject *HAspinbuttonMois_adj;
  GtkWidget *HAspinbuttonMois;
  GtkObject *HAspinbuttonAnnee_adj;
  GtkWidget *HAspinbuttonAnnee;
  GtkObject *HAspinbuttonNbreSiege_adj;
  GtkWidget *HAspinbuttonNbreSiege;
  GtkWidget *HAlabelDatearrive;
  GtkWidget *HAlabelAnnee;
  GtkWidget *HAlabelMois;
  GtkWidget *HAlabelJour;
  GtkWidget *HAlabelPrix;
  GtkWidget *HAlabelNbreSiege;
  GtkWidget *HAlabelCompagnie;
  GtkWidget *HAlabelDatedepart;
  GtkWidget *HAlabelDestination;
  GtkWidget *HAlabelDepart;
  GtkWidget *HAbuttonAfficher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label18;
  GtkWidget *HAbuttonAjout;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label17;
  GtkWidget *HAlabelPrenom;
  GtkWidget *HAlabelCin;
  GtkWidget *HAlabelNom;
  GtkWidget *HAlabelDateres;
  GtkWidget *HAchoix;
  GtkWidget *HAbuttonRemplir;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label40;
  GtkWidget *HAcomboboxDepart;
  GtkWidget *HAcomboboxDestination;
  GtkWidget *HAcomboboxDatearrive;
  GtkWidget *HAcomboboxDatedepart;
  GtkWidget *HAcomboboxCompagnie;
  GtkWidget *HAcomboboxPrix;
  GtkWidget *HAbuttonConfirmerd;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label42;
  GtkWidget *HAbuttonConfirmerp;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label41;

  HAFenetreReservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (HAFenetreReservation), _("FenetreReservation"));

  HAfixed1 = gtk_fixed_new ();
  gtk_widget_show (HAfixed1);
  gtk_container_add (GTK_CONTAINER (HAFenetreReservation), HAfixed1);
  gtk_widget_set_size_request (HAfixed1, 1440, 900);

  HAentryNom = gtk_entry_new ();
  gtk_widget_show (HAentryNom);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAentryNom, 624, 216);
  gtk_widget_set_size_request (HAentryNom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (HAentryNom), 8226);

  HAentryPrenom = gtk_entry_new ();
  gtk_widget_show (HAentryPrenom);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAentryPrenom, 624, 272);
  gtk_widget_set_size_request (HAentryPrenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (HAentryPrenom), 8226);

  HAentryCin = gtk_entry_new ();
  gtk_widget_show (HAentryCin);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAentryCin, 624, 328);
  gtk_widget_set_size_request (HAentryCin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (HAentryCin), 8226);

  HAspinbuttonJour_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  HAspinbuttonJour = gtk_spin_button_new (GTK_ADJUSTMENT (HAspinbuttonJour_adj), 1, 0);
  gtk_widget_show (HAspinbuttonJour);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAspinbuttonJour, 608, 400);
  gtk_widget_set_size_request (HAspinbuttonJour, 60, 27);

  HAspinbuttonMois_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  HAspinbuttonMois = gtk_spin_button_new (GTK_ADJUSTMENT (HAspinbuttonMois_adj), 1, 0);
  gtk_widget_show (HAspinbuttonMois);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAspinbuttonMois, 784, 400);
  gtk_widget_set_size_request (HAspinbuttonMois, 60, 27);

  HAspinbuttonAnnee_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  HAspinbuttonAnnee = gtk_spin_button_new (GTK_ADJUSTMENT (HAspinbuttonAnnee_adj), 1, 0);
  gtk_widget_show (HAspinbuttonAnnee);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAspinbuttonAnnee, 976, 400);
  gtk_widget_set_size_request (HAspinbuttonAnnee, 60, 27);

  HAspinbuttonNbreSiege_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  HAspinbuttonNbreSiege = gtk_spin_button_new (GTK_ADJUSTMENT (HAspinbuttonNbreSiege_adj), 1, 0);
  gtk_widget_show (HAspinbuttonNbreSiege);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAspinbuttonNbreSiege, 856, 664);
  gtk_widget_set_size_request (HAspinbuttonNbreSiege, 60, 27);

  HAlabelDatearrive = gtk_label_new (_("Date d'arriv\303\251: "));
  gtk_widget_show (HAlabelDatearrive);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelDatearrive, 808, 592);
  gtk_widget_set_size_request (HAlabelDatearrive, 112, 32);

  HAlabelAnnee = gtk_label_new (_("Ann\303\251e: "));
  gtk_widget_show (HAlabelAnnee);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelAnnee, 912, 400);
  gtk_widget_set_size_request (HAlabelAnnee, 56, 24);

  HAlabelMois = gtk_label_new (_("Mois: "));
  gtk_widget_show (HAlabelMois);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelMois, 736, 400);
  gtk_widget_set_size_request (HAlabelMois, 40, 24);

  HAlabelJour = gtk_label_new (_("Jour: "));
  gtk_widget_show (HAlabelJour);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelJour, 560, 400);
  gtk_widget_set_size_request (HAlabelJour, 40, 24);

  HAlabelPrix = gtk_label_new (_("Prix:"));
  gtk_widget_show (HAlabelPrix);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelPrix, 944, 656);
  gtk_widget_set_size_request (HAlabelPrix, 48, 32);

  HAlabelNbreSiege = gtk_label_new (_("Nombre de si\303\251ge:"));
  gtk_widget_show (HAlabelNbreSiege);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelNbreSiege, 728, 664);
  gtk_widget_set_size_request (HAlabelNbreSiege, 128, 24);

  HAlabelCompagnie = gtk_label_new (_("Compagnie: "));
  gtk_widget_show (HAlabelCompagnie);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelCompagnie, 440, 656);
  gtk_widget_set_size_request (HAlabelCompagnie, 104, 32);

  HAlabelDatedepart = gtk_label_new (_("Date de d\303\251part: "));
  gtk_widget_show (HAlabelDatedepart);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelDatedepart, 464, 592);
  gtk_widget_set_size_request (HAlabelDatedepart, 120, 32);

  HAlabelDestination = gtk_label_new (_("Destination: "));
  gtk_widget_show (HAlabelDestination);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelDestination, 832, 528);
  gtk_widget_set_size_request (HAlabelDestination, 88, 32);

  HAlabelDepart = gtk_label_new (_("D\303\251part: "));
  gtk_widget_show (HAlabelDepart);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelDepart, 416, 528);
  gtk_widget_set_size_request (HAlabelDepart, 64, 32);

  HAbuttonAfficher = gtk_button_new ();
  gtk_widget_show (HAbuttonAfficher);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAbuttonAfficher, 760, 736);
  gtk_widget_set_size_request (HAbuttonAfficher, 88, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (HAbuttonAfficher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox3), label18, FALSE, FALSE, 0);

  HAbuttonAjout = gtk_button_new ();
  gtk_widget_show (HAbuttonAjout);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAbuttonAjout, 648, 736);
  gtk_widget_set_size_request (HAbuttonAjout, 88, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (HAbuttonAjout), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox2), label17, FALSE, FALSE, 0);

  HAlabelPrenom = gtk_label_new (_("Prenom: "));
  gtk_widget_show (HAlabelPrenom);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelPrenom, 544, 272);
  gtk_widget_set_size_request (HAlabelPrenom, 72, 24);

  HAlabelCin = gtk_label_new (_("Cin: "));
  gtk_widget_show (HAlabelCin);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelCin, 544, 328);
  gtk_widget_set_size_request (HAlabelCin, 40, 24);

  HAlabelNom = gtk_label_new (_("Nom: "));
  gtk_widget_show (HAlabelNom);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelNom, 544, 216);
  gtk_widget_set_size_request (HAlabelNom, 48, 24);

  HAlabelDateres = gtk_label_new (_("Date de r\303\251servation: "));
  gtk_widget_show (HAlabelDateres);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAlabelDateres, 368, 400);
  gtk_widget_set_size_request (HAlabelDateres, 144, 16);

  HAchoix = gtk_label_new (_("Cliquer sur la bouton \"Remplir' pour choisir une vol: "));
  gtk_widget_show (HAchoix);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAchoix, 432, 472);
  gtk_widget_set_size_request (HAchoix, 416, 32);
  gtk_label_set_justify (GTK_LABEL (HAchoix), GTK_JUSTIFY_CENTER);

  HAbuttonRemplir = gtk_button_new ();
  gtk_widget_show (HAbuttonRemplir);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAbuttonRemplir, 816, 472);
  gtk_widget_set_size_request (HAbuttonRemplir, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (HAbuttonRemplir), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Remplir"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox9), label40, FALSE, FALSE, 0);

  HAcomboboxDepart = gtk_combo_box_new_text ();
  gtk_widget_show (HAcomboboxDepart);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAcomboboxDepart, 480, 528);
  gtk_widget_set_size_request (HAcomboboxDepart, 192, 32);

  HAcomboboxDestination = gtk_combo_box_new_text ();
  gtk_widget_show (HAcomboboxDestination);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAcomboboxDestination, 920, 528);
  gtk_widget_set_size_request (HAcomboboxDestination, 200, 32);

  HAcomboboxDatearrive = gtk_combo_box_new_text ();
  gtk_widget_show (HAcomboboxDatearrive);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAcomboboxDatearrive, 920, 592);
  gtk_widget_set_size_request (HAcomboboxDatearrive, 192, 32);

  HAcomboboxDatedepart = gtk_combo_box_new_text ();
  gtk_widget_show (HAcomboboxDatedepart);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAcomboboxDatedepart, 584, 592);
  gtk_widget_set_size_request (HAcomboboxDatedepart, 168, 32);

  HAcomboboxCompagnie = gtk_combo_box_new_text ();
  gtk_widget_show (HAcomboboxCompagnie);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAcomboboxCompagnie, 552, 656);
  gtk_widget_set_size_request (HAcomboboxCompagnie, 144, 32);

  HAcomboboxPrix = gtk_combo_box_new_text ();
  gtk_widget_show (HAcomboboxPrix);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAcomboboxPrix, 992, 656);
  gtk_widget_set_size_request (HAcomboboxPrix, 160, 32);

  HAbuttonConfirmerd = gtk_button_new ();
  gtk_widget_show (HAbuttonConfirmerd);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAbuttonConfirmerd, 1128, 528);
  gtk_widget_set_size_request (HAbuttonConfirmerd, 96, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (HAbuttonConfirmerd), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox11), label42, FALSE, FALSE, 0);

  HAbuttonConfirmerp = gtk_button_new ();
  gtk_widget_show (HAbuttonConfirmerp);
  gtk_fixed_put (GTK_FIXED (HAfixed1), HAbuttonConfirmerp, 680, 528);
  gtk_widget_set_size_request (HAbuttonConfirmerp, 96, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (HAbuttonConfirmerp), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox10), label41, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) HAbuttonAfficher, "clicked",
                    G_CALLBACK (on_HAbuttonAfficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) HAbuttonAjout, "clicked",
                    G_CALLBACK (on_HAbuttonAjout_clicked),
                    NULL);
  g_signal_connect ((gpointer) HAbuttonRemplir, "clicked",
                    G_CALLBACK (on_HAbuttonRemplir_clicked),
                    NULL);
  g_signal_connect ((gpointer) HAbuttonConfirmerd, "clicked",
                    G_CALLBACK (on_HAbuttonConfirmerd_clicked),
                    NULL);
  g_signal_connect ((gpointer) HAbuttonConfirmerp, "clicked",
                    G_CALLBACK (on_HAbuttonConfirmerp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (HAFenetreReservation, HAFenetreReservation, "HAFenetreReservation");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAfixed1, "HAfixed1");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAentryNom, "HAentryNom");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAentryPrenom, "HAentryPrenom");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAentryCin, "HAentryCin");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAspinbuttonJour, "HAspinbuttonJour");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAspinbuttonMois, "HAspinbuttonMois");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAspinbuttonAnnee, "HAspinbuttonAnnee");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAspinbuttonNbreSiege, "HAspinbuttonNbreSiege");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelDatearrive, "HAlabelDatearrive");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelAnnee, "HAlabelAnnee");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelMois, "HAlabelMois");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelJour, "HAlabelJour");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelPrix, "HAlabelPrix");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelNbreSiege, "HAlabelNbreSiege");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelCompagnie, "HAlabelCompagnie");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelDatedepart, "HAlabelDatedepart");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelDestination, "HAlabelDestination");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelDepart, "HAlabelDepart");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAbuttonAfficher, "HAbuttonAfficher");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, image3, "image3");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, label18, "label18");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAbuttonAjout, "HAbuttonAjout");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, image2, "image2");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, label17, "label17");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelPrenom, "HAlabelPrenom");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelCin, "HAlabelCin");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelNom, "HAlabelNom");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAlabelDateres, "HAlabelDateres");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAchoix, "HAchoix");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAbuttonRemplir, "HAbuttonRemplir");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, image10, "image10");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, label40, "label40");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAcomboboxDepart, "HAcomboboxDepart");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAcomboboxDestination, "HAcomboboxDestination");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAcomboboxDatearrive, "HAcomboboxDatearrive");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAcomboboxDatedepart, "HAcomboboxDatedepart");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAcomboboxCompagnie, "HAcomboboxCompagnie");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAcomboboxPrix, "HAcomboboxPrix");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAbuttonConfirmerd, "HAbuttonConfirmerd");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, image12, "image12");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, label42, "label42");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, HAbuttonConfirmerp, "HAbuttonConfirmerp");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, image11, "image11");
  GLADE_HOOKUP_OBJECT (HAFenetreReservation, label41, "label41");

  return HAFenetreReservation;
}

GtkWidget*
create_HAFenetreAffichage (void)
{
  GtkWidget *HAFenetreAffichage;
  GtkWidget *fixed2;
  GtkWidget *HAtreeview;
  GtkWidget *HAbuttonModifier;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label36;
  GtkWidget *HAbuttonSupprimer;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label37;
  GtkWidget *HAbuttonRetour;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label38;

  HAFenetreAffichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (HAFenetreAffichage), _("FenetreAffichage"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (HAFenetreAffichage), fixed2);
  gtk_widget_set_size_request (fixed2, 1440, 900);

  HAtreeview = gtk_tree_view_new ();
  gtk_widget_show (HAtreeview);
  gtk_fixed_put (GTK_FIXED (fixed2), HAtreeview, 80, 144);
  gtk_widget_set_size_request (HAtreeview, 1304, 344);

  HAbuttonModifier = gtk_button_new ();
  gtk_widget_show (HAbuttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed2), HAbuttonModifier, 536, 576);
  gtk_widget_set_size_request (HAbuttonModifier, 88, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (HAbuttonModifier), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox6), label36, FALSE, FALSE, 0);

  HAbuttonSupprimer = gtk_button_new ();
  gtk_widget_show (HAbuttonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), HAbuttonSupprimer, 656, 576);
  gtk_widget_set_size_request (HAbuttonSupprimer, 104, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (HAbuttonSupprimer), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox7), label37, FALSE, FALSE, 0);

  HAbuttonRetour = gtk_button_new ();
  gtk_widget_show (HAbuttonRetour);
  gtk_fixed_put (GTK_FIXED (fixed2), HAbuttonRetour, 792, 576);
  gtk_widget_set_size_request (HAbuttonRetour, 88, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (HAbuttonRetour), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox8), label38, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) HAbuttonModifier, "clicked",
                    G_CALLBACK (on_HAbuttonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) HAbuttonSupprimer, "clicked",
                    G_CALLBACK (on_HAbuttonSupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) HAbuttonRetour, "clicked",
                    G_CALLBACK (on_HAbuttonRetour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (HAFenetreAffichage, HAFenetreAffichage, "HAFenetreAffichage");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, HAtreeview, "HAtreeview");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, HAbuttonModifier, "HAbuttonModifier");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, image6, "image6");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, label36, "label36");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, HAbuttonSupprimer, "HAbuttonSupprimer");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, image7, "image7");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, label37, "label37");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, HAbuttonRetour, "HAbuttonRetour");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, image8, "image8");
  GLADE_HOOKUP_OBJECT (HAFenetreAffichage, label38, "label38");

  return HAFenetreAffichage;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *button1;
  GtkWidget *button3;
  GtkWidget *label39;
  GtkWidget *button4;
  GtkWidget *image9;
  GtkWidget *button2;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window3, 1440, 900);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  button1 = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed3), button1, 568, 440);
  gtk_widget_set_size_request (button1, 66, 29);

  button3 = gtk_button_new_with_mnemonic (_("button3"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 832, 552);
  gtk_widget_set_size_request (button3, 66, 29);

  label39 = gtk_label_new (_("label39"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed3), label39, 368, 608);
  gtk_widget_set_size_request (label39, 49, 17);

  button4 = gtk_button_new_with_mnemonic (_("button4"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 480, 552);
  gtk_widget_set_size_request (button4, 66, 29);

  image9 = create_pixmap (window3, "voyages-2.jpg");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed3), image9, 0, 0);
  gtk_widget_set_size_request (image9, 1440, 900);
  GTK_WIDGET_SET_FLAGS (image9, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (image9, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_with_mnemonic (_("button2"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed3), button2, 656, 400);
  gtk_widget_set_size_request (button2, 66, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, button1, "button1");
  GLADE_HOOKUP_OBJECT (window3, button3, "button3");
  GLADE_HOOKUP_OBJECT (window3, label39, "label39");
  GLADE_HOOKUP_OBJECT (window3, button4, "button4");
  GLADE_HOOKUP_OBJECT (window3, image9, "image9");
  GLADE_HOOKUP_OBJECT (window3, button2, "button2");

  gtk_widget_grab_focus (image9);
  gtk_widget_grab_default (image9);
  return window3;
}

