/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_HAFenetreReservation (void);
GtkWidget* create_HAFenetreAffichage (void);
GtkWidget* create_HAMenuAgent (void);
GtkWidget* create_HAFenetreModification (void);
GtkWidget* create_HAFenetreRecherchevol (void);
GtkWidget* create_HAFenetreReservationvoiture (void);
GtkWidget* create_HAFenetreAffichagevoiture (void);
GtkWidget* create_HAFenetreModificationVoiture (void);
GtkWidget* create_HAFenetreRechercheVoiture (void);
